
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Aug 26 16:39:26 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQUALITY = 30;
  public static final int CONST = 10;
  public static final int LPAREN = 44;
  public static final int SEMI = 41;
  public static final int GREATER = 32;
  public static final int CONTINUE = 9;
  public static final int LESS = 34;
  public static final int RPAREN = 45;
  public static final int AND = 36;
  public static final int RECORD = 12;
  public static final int OR = 37;
  public static final int COMMA = 42;
  public static final int DDOT = 50;
  public static final int CLASS = 14;
  public static final int INC = 39;
  public static final int DIV = 28;
  public static final int LESSEQ = 35;
  public static final int IF = 20;
  public static final int THIS = 16;
  public static final int DOT = 43;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int EQUAL = 38;
  public static final int SUPER = 15;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MUL = 27;
  public static final int ADD = 25;
  public static final int NUMBER = 3;
  public static final int MOD = 29;
  public static final int BREAK = 7;
  public static final int IDENT = 2;
  public static final int VOID = 11;
  public static final int LBRACE = 46;
  public static final int ELSE = 19;
  public static final int LSQUARE = 48;
  public static final int ENUM = 13;
  public static final int READ = 24;
  public static final int GOTO = 51;
  public static final int RSQUARE = 49;
  public static final int CHARCONST = 4;
  public static final int WHILE = 22;
  public static final int RBRACE = 47;
  public static final int BOOLCONST = 5;
  public static final int EXTENDS = 17;
  public static final int PROG = 6;
  public static final int BINARY = 52;
  public static final int GREATEREQ = 33;
  public static final int DEC = 40;
  public static final int NOEQUALITY = 31;
  public static final int SUB = 26;
  public static final int PRINT = 23;
  public static final int DO = 21;
}

