package rs.ac.bg.etf.pp1;


public class sym_old {
  public static final int PROG = 1;
  public static final int BREAK = 2;
  public static final int CLASS = 3;
  public static final int ENUM = 4;
  public static final int ELSE = 5;
  public static final int CONST = 6;
  public static final int IF = 7;
  public static final int DO = 8;
  public static final int WHILE = 9;
  public static final int NEW = 10;
  public static final int PRINT = 11;
  public static final int READ = 12;
  public static final int RETURN = 13;
  public static final int VOID = 14;
  public static final int EXTENDS = 15;
  public static final int CONTINUE = 16;
  public static final int THIS = 17;
  public static final int SUPER = 18;
  public static final int GOTO = 19;
  public static final int RECORD = 20;
  public static final int ADD = 21;
  public static final int SUB = 22;
  public static final int MUL = 23;
  public static final int DIV = 24;
  public static final int MOD = 25;
  public static final int EQUALITY = 26;
  public static final int NOEQUALITY = 27;
  public static final int GREATER = 28;
  public static final int GREATEREQ = 29;
  public static final int LESS = 30;
  public static final int LESSEQ = 31;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int EQUAL = 34;
  public static final int INC = 35;
  public static final int DEC = 36;
  public static final int SEMI = 37;
  public static final int DDOT = 38;
  public static final int COMMA = 39;
  public static final int DOT = 40;
  public static final int LPAREN = 41;
  public static final int RPAREN = 42;
  public static final int LSQUARE = 43;
  public static final int RSQUARE = 44;
  public static final int LBRACE = 45;
  public static final int RBRACE = 46;
  public static final int BOOLCONST = 47;
  public static final int IDENT = 48;
  public static final int NUMBER = 49;
  public static final int CHARCONST = 50;
  public static final int EOF = 51;
  public static final int BINARY = 52;
}